"""
Browser tests for the page itself.

Everything else in this repo drives the API. That leaves the part a user actually
touches untested: whether a citation renders as a chip, whether clicking it opens
the source panel and fetches the page image, whether the tabs switch, whether the
upload flow enables the composer. None of that is reachable from an HTTP client,
and all of it has broken silently before - the answer renderer was rewritten
twice.

The app is started in-process on a spare port with the real Weaviate behind it,
so this exercises the shipped page against real answers rather than fixtures.

    python tests/test_ui.py            # headless
    python tests/test_ui.py --headed   # watch it drive the browser

Skips cleanly if Playwright has no browser installed, so it never blocks a run
on a machine that has not set one up.
"""

from __future__ import annotations

import socket
import sys
import threading
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

HEADED = "--headed" in sys.argv
# Answers are generated by a local model, so a turn can take a few seconds.
ANSWER_TIMEOUT_MS = 120_000
# Ingestion is Docling plus two LLM passes per paper, and the library upload
# test sends two, so it needs a much longer leash than an answer does.
INGEST_TIMEOUT_MS = 420_000


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class Server:
    """Run the real app in a background thread on its own port."""

    def __init__(self):
        self.port = _free_port()
        self._server = None

    def __enter__(self):
        import uvicorn
        import app as appmod

        config = uvicorn.Config(appmod.app, host="127.0.0.1", port=self.port,
                                log_level="error")
        self._server = uvicorn.Server(config)
        threading.Thread(target=self._server.run, daemon=True).start()
        for _ in range(120):
            if self._server.started:
                break
            time.sleep(0.5)
        else:
            raise RuntimeError("server did not start")
        return self

    def __exit__(self, *_):
        if self._server:
            self._server.should_exit = True
            time.sleep(1.0)

    @property
    def url(self) -> str:
        return f"http://127.0.0.1:{self.port}/"


CHECKS: list[tuple[str, str]] = []


def check(name: str, ok: bool, detail: str = ""):
    CHECKS.append((name, "ok" if ok else "FAIL"))
    print(f"  {'ok  ' if ok else 'FAIL'} {name}{'  ' + detail if detail else ''}")


def run(page, base_url):
    page.goto(base_url, wait_until="domcontentloaded")

    # -- the shell renders and knows what the library holds -------------------
    check("page title", page.title() == "Research RAG")
    page.wait_for_function("() => document.getElementById('health').textContent.includes('chunks')",
                           timeout=60_000)
    health = page.inner_text("#health")
    check("header reports the corpus", "paper" in health and "chunks" in health, health)

    # Browsers request this on every page load whether the page asks or not,
    # so a missing route logged a 404 for every single visit.
    fav = page.context.request.get(base_url + "favicon.ico")
    check("favicon is served", fav.status == 200, f"HTTP {fav.status}")

    # The page is the whole UI. Served without a cache directive, browsers kept
    # it under heuristic caching and never asked whether it had changed, so
    # shipped features stayed invisible until a hard reload.
    shell = page.context.request.get(base_url)
    cc = shell.headers.get("cache-control") or ""
    check("the page must be revalidated, not cached blindly",
          "no-cache" in cc or "no-store" in cc, cc or "(no directive)")

    # -- tabs switch, and only one view is visible ---------------------------
    for tab in ["paper", "scratch", "library", "ask"]:
        page.click(f'.tab-btn[data-tab="{tab}"]')
        visible = page.eval_on_selector_all(
            ".view", "vs => vs.filter(v => v.classList.contains('active')).map(v => v.id)")
        check(f"tab '{tab}' shows exactly its own view",
              visible == [f"tab-{tab}"], str(visible))

    # -- the library list is populated from the API --------------------------
    page.click('.tab-btn[data-tab="library"]')
    page.wait_for_function("() => document.querySelectorAll('#lib-list > div').length > 0",
                           timeout=30_000)
    n_lib = page.eval_on_selector_all("#lib-list > div", "d => d.length")
    check("library lists papers", n_lib > 0, f"{n_lib} rows")

    # the single-paper tab's dropdown is filled from the same source
    page.click('.tab-btn[data-tab="paper"]')
    n_opts = page.eval_on_selector_all("#paper-select option", "o => o.length")
    check("paper selector is populated", n_opts > 1, f"{n_opts - 1} papers")

    # -- ask a real question and inspect the rendered answer -----------------
    page.click('.tab-btn[data-tab="ask"]')
    page.fill("#ask-input", "Which word embedding models are used across these papers?")
    page.click("#ask-form button[type=submit], #ask-form button:not([type=button])")
    page.wait_for_selector("#ask-thread .answer", timeout=ANSWER_TIMEOUT_MS)

    answer = page.inner_text("#ask-thread .answer")
    check("answer rendered", len(answer) > 40, f"{len(answer)} chars")

    n_chips = page.eval_on_selector_all("#ask-thread .cite", "c => c.length")
    check("citations render as chips", n_chips > 0, f"{n_chips} chips")

    n_sources = page.eval_on_selector_all("#ask-thread button:has(.badge)", "b => b.length")
    check("source list rendered", n_sources > 0, f"{n_sources} sources")

    # Model output must never become markup.
    injected = page.eval_on_selector_all("#ask-thread script", "s => s.length")
    check("no script injected from model output", injected == 0)

    # -- clicking a citation opens the panel and renders the PDF page --------
    if n_chips:
        page.click("#ask-thread .cite >> nth=0")
        check("source panel opens", page.is_visible("#src-panel"))
        page.wait_for_selector("#src-img:not(.hidden), #src-text:not(.hidden)",
                               timeout=60_000)
        rendered = page.eval_on_selector(
            "#src-img", "i => !i.classList.contains('hidden') && i.naturalWidth > 0")
        check("citation renders the source page", bool(rendered))
        check("clicked chip is highlighted",
              page.eval_on_selector_all("#ask-thread .cite.on", "c => c.length") == 1)
        check("panel names the source", len(page.inner_text("#src-title")) > 0,
              page.inner_text("#src-title")[:40])

        # Zoom has to change the rendered width, not just the label. A global
        # `img { max-width: 100% }` once capped the image at its container, so
        # the percentage counted up while the page stayed exactly the same size.
        before = page.eval_on_selector("#src-img", "i => i.getBoundingClientRect().width")
        page.click("#src-zoom-in")
        page.wait_for_timeout(250)
        after = page.eval_on_selector("#src-img", "i => i.getBoundingClientRect().width")
        check("zooming in actually enlarges the page",
              after > before + 1, f"{before:.0f}px -> {after:.0f}px")
        page.click("#src-zoom-out")
        page.wait_for_timeout(250)
        back = page.eval_on_selector("#src-img", "i => i.getBoundingClientRect().width")
        check("zooming out shrinks it again", back < after - 1,
              f"{after:.0f}px -> {back:.0f}px")
        page.click("#src-close")
        check("panel closes", not page.is_visible("#src-panel"))

    # -- the composer is disabled until something is uploaded ----------------
    page.click('.tab-btn[data-tab="scratch"]')
    check("scratch composer disabled before upload",
          page.get_attribute("#scratch-input", "disabled") is not None)

    # -- clearing a thread returns it to its empty state ---------------------
    # Not "leaves it blank": an empty thread now offers the starting guidance
    # and example questions, which is what a first-time visitor sees too.
    page.click('.tab-btn[data-tab="ask"]')
    page.click("#ask-clear")
    check("clear removes every turn",
          page.eval_on_selector_all("#ask-thread .turn", "t => t.length") == 0)
    check("clear restores the empty state",
          page.eval_on_selector_all("#ask-thread .empty", "e => e.length") == 1)
    check("the empty state offers example questions",
          page.eval_on_selector_all("#ask-thread .exq", "e => e.length") > 0)

    library_checks(page)

    # -- the page never logged an error -------------------------------------
    check("no console errors", not ERRORS, "; ".join(ERRORS[:2]))


def library_checks(page):
    """
    Upload two throwaway papers, then bulk-remove them.

    Both halves are browser-only: the progress bar's states exist nowhere in
    the API, and multi-select is entirely client-side bookkeeping that has to
    survive the list re-rendering after every delete. Using generated one-page
    PDFs keeps it to seconds and leaves the real library exactly as it was.
    """
    from test_paper_lifecycle import make_pdf

    tmp = Path(__file__).resolve().parent / "_tmp_ui"
    tmp.mkdir(exist_ok=True)
    names = ["zz_ui_probe_a.pdf", "zz_ui_probe_b.pdf"]
    paths = []
    for n in names:
        f = tmp / n
        make_pdf(f, "A probe paper with 1234 samples and 55.5 percent accuracy.")
        paths.append(str(f))

    page.on("dialog", lambda d: d.accept())
    page.click('.tab-btn[data-tab="library"]')
    before = page.eval_on_selector_all("#lib-list > div", "d => d.length")

    # -- upload, and watch the bar rather than just the outcome ------------
    page.set_input_files("#lib-file", paths)
    page.wait_for_selector("#lib-status .bar", timeout=15_000)
    check("a progress bar appears while uploading", True)
    check("progress is counted in papers, not bytes",
          "of 2 done" in page.inner_text("#lib-status"),
          page.inner_text("#lib-status").splitlines()[0][:60])

    # the bar must go indeterminate while the server is parsing, since there
    # is no percentage to report during that wait
    try:
        page.wait_for_selector("#lib-status .bar.indet", timeout=60_000)
        check("the bar goes indeterminate while parsing", True)
    except Exception:
        check("the bar goes indeterminate while parsing", False, "never seen")

    page.wait_for_function(
        "() => (document.querySelector('#lib-status')||{}).textContent"
        "        ?.includes('papers added')",
        timeout=INGEST_TIMEOUT_MS)
    summary = page.inner_text("#lib-status").splitlines()[0]
    check("the batch reports what it added", "2 of 2 papers added" in summary,
          summary[:60])
    check("progress bar ends full",
          page.eval_on_selector("#lib-status .bar > i",
                                "i => i.style.width === '100%'"))

    page.wait_for_function("n => document.querySelectorAll('#lib-list > div').length >= n",
                           arg=before + 2, timeout=30_000)
    check("uploaded papers appear in the library",
          page.eval_on_selector_all("#lib-list > div", "d => d.length") == before + 2)

    # A paper is shown by what it is called, not by what the file is called.
    shown = page.eval_on_selector_all(
        "#lib-list > div",
        "rows => rows.filter(r => (r.querySelector('label')?.title || '')"
        "                          .startsWith('zz_ui_probe'))"
        "            .map(r => r.querySelector('label')?.textContent || '')")
    check("papers are listed by their resolved title",
          bool(shown) and all("zz_ui_probe" not in t for t in shown),
          str(shown[:2]))

    # -- the filter, which is the only way through a library this size -----
    page.fill("#lib-filter", "zz ui probe")
    page.wait_for_function(
        "() => document.querySelectorAll('#lib-list > div').length === 2",
        timeout=5_000)
    check("the filter narrows the list to matches", True, "2 of many")
    page.fill("#lib-filter", "zzzz-no-such-paper")
    page.wait_for_timeout(150)
    check("an unmatched filter says so",
          "No paper matches" in page.inner_text("#lib-list"))
    page.fill("#lib-filter", "")
    page.wait_for_function("n => document.querySelectorAll('#lib-list > div').length === n",
                           arg=before + 2, timeout=5_000)
    check("clearing the filter restores every row", True)

    # -- multi-select -----------------------------------------------------
    check("the remove button starts disabled",
          page.get_attribute("#lib-remove", "disabled") is not None)

    page.click("#lib-all")
    total = before + 2
    label = page.inner_text("#lib-remove")
    check("select all selects every paper", f"Remove {total} papers" == label, label)

    page.click("#lib-all")  # and clears again
    check("clearing the selection disables removal",
          page.get_attribute("#lib-remove", "disabled") is not None,
          page.inner_text("#lib-remove"))

    # tick just the two probes
    picked = page.eval_on_selector_all(
        "#lib-list > div",
        """rows => {
             let n = 0;
             for (const r of rows) {
               // The visible text is the paper's real title now; the filename
               // lives on the label's title attribute and is what identifies
               // a row unambiguously.
               const f = r.querySelector('label')?.title || '';
               if (f.startsWith('zz_ui_probe')) {
                 r.querySelector('input[type=checkbox]').click(); n++;
               }
             }
             return n;
           }""")
    check("individual rows can be selected", picked == 2, f"{picked} ticked")
    check("the button counts the selection",
          page.inner_text("#lib-remove").strip() == "Remove 2 papers",
          page.inner_text("#lib-remove"))
    check("select-all shows a partial state",
          page.eval_on_selector("#lib-all", "c => c.indeterminate"))

    # -- bulk remove ------------------------------------------------------
    page.click("#lib-remove")
    page.wait_for_function("n => document.querySelectorAll('#lib-list > div').length === n",
                           arg=before, timeout=120_000)
    check("bulk remove deletes every selected paper", True, f"back to {before}")
    left = page.eval_on_selector_all(
        "#lib-list > div",
        "rows => rows.map(r => r.querySelector('label')?.title || '')"
        "          .filter(f => f.startsWith('zz_ui_probe'))")
    check("no probe survives the bulk remove", left == [], str(left))
    check("the toolbar resets after removal",
          page.get_attribute("#lib-remove", "disabled") is not None)

    for f in paths:
        Path(f).unlink(missing_ok=True)
    try:
        tmp.rmdir()
    except OSError:
        pass


ERRORS: list[str] = []


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("playwright not installed - skipping UI tests")
        return 0

    with Server() as server:
        with sync_playwright() as p:
            try:
                browser = p.chromium.launch(headless=not HEADED)
            except Exception as exc:
                print(f"no browser available, skipping UI tests: "
                      f"{str(exc).splitlines()[0][:80]}")
                return 0
            page = browser.new_page(viewport={"width": 1400, "height": 900})
            page.on("console", lambda m: ERRORS.append(m.text)
                    if m.type == "error" else None)
            page.on("pageerror", lambda e: ERRORS.append(str(e)))
            try:
                run(page, server.url)
            except Exception as exc:
                # A failed check often makes the next step impossible - with no
                # tab active there is nothing to type into - and an exception
                # here would otherwise discard the checks that did run.
                check("run completed", False, f"{type(exc).__name__}: "
                                              f"{str(exc).splitlines()[0][:90]}")
            finally:
                browser.close()

    failed = sum(1 for _, s in CHECKS if s == "FAIL")
    print(f"\n{len(CHECKS) - failed}/{len(CHECKS)} UI check(s) passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
