"""
Browser tests for the page itself.

Everything else in this repo drives the API. That leaves the part a user actually
touches untested: whether a citation renders as a chip, whether clicking it opens
the source panel and fetches the page image, whether the tabs switch, whether the
upload flow enables the composer. None of that is reachable from an HTTP client,
and all of it has broken silently before - the answer renderer was rewritten
twice.

The app is started in-process on a spare port with the real Weaviate behind it,
so this exercises the shipped page against real answers rather than fixtures.

    python tests/test_ui.py            # headless
    python tests/test_ui.py --headed   # watch it drive the browser

Skips cleanly if Playwright has no browser installed, so it never blocks a run
on a machine that has not set one up.
"""

from __future__ import annotations

import socket
import sys
import threading
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

HEADED = "--headed" in sys.argv
# Answers are generated by a local model, so a turn can take a few seconds.
ANSWER_TIMEOUT_MS = 120_000


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class Server:
    """Run the real app in a background thread on its own port."""

    def __init__(self):
        self.port = _free_port()
        self._server = None

    def __enter__(self):
        import uvicorn
        import app as appmod

        config = uvicorn.Config(appmod.app, host="127.0.0.1", port=self.port,
                                log_level="error")
        self._server = uvicorn.Server(config)
        threading.Thread(target=self._server.run, daemon=True).start()
        for _ in range(120):
            if self._server.started:
                break
            time.sleep(0.5)
        else:
            raise RuntimeError("server did not start")
        return self

    def __exit__(self, *_):
        if self._server:
            self._server.should_exit = True
            time.sleep(1.0)

    @property
    def url(self) -> str:
        return f"http://127.0.0.1:{self.port}/"


CHECKS: list[tuple[str, str]] = []


def check(name: str, ok: bool, detail: str = ""):
    CHECKS.append((name, "ok" if ok else "FAIL"))
    print(f"  {'ok  ' if ok else 'FAIL'} {name}{'  ' + detail if detail else ''}")


def run(page, base_url):
    page.goto(base_url, wait_until="domcontentloaded")

    # -- the shell renders and knows what the library holds -------------------
    check("page title", page.title() == "Research RAG")
    page.wait_for_function("() => document.getElementById('health').textContent.includes('chunks')",
                           timeout=60_000)
    health = page.inner_text("#health")
    check("header reports the corpus", "paper" in health and "chunks" in health, health)

    # -- tabs switch, and only one view is visible ---------------------------
    for tab in ["paper", "scratch", "library", "ask"]:
        page.click(f'.tab-btn[data-tab="{tab}"]')
        visible = page.eval_on_selector_all(
            ".view", "vs => vs.filter(v => v.classList.contains('active')).map(v => v.id)")
        check(f"tab '{tab}' shows exactly its own view",
              visible == [f"tab-{tab}"], str(visible))

    # -- the library list is populated from the API --------------------------
    page.click('.tab-btn[data-tab="library"]')
    page.wait_for_function("() => document.querySelectorAll('#lib-list > div').length > 0",
                           timeout=30_000)
    n_lib = page.eval_on_selector_all("#lib-list > div", "d => d.length")
    check("library lists papers", n_lib > 0, f"{n_lib} rows")

    # the single-paper tab's dropdown is filled from the same source
    page.click('.tab-btn[data-tab="paper"]')
    n_opts = page.eval_on_selector_all("#paper-select option", "o => o.length")
    check("paper selector is populated", n_opts > 1, f"{n_opts - 1} papers")

    # -- ask a real question and inspect the rendered answer -----------------
    page.click('.tab-btn[data-tab="ask"]')
    page.fill("#ask-input", "Which word embedding models are used across these papers?")
    page.click("#ask-form button[type=submit], #ask-form button:not([type=button])")
    page.wait_for_selector("#ask-thread .answer", timeout=ANSWER_TIMEOUT_MS)

    answer = page.inner_text("#ask-thread .answer")
    check("answer rendered", len(answer) > 40, f"{len(answer)} chars")

    n_chips = page.eval_on_selector_all("#ask-thread .cite", "c => c.length")
    check("citations render as chips", n_chips > 0, f"{n_chips} chips")

    n_sources = page.eval_on_selector_all("#ask-thread button:has(.badge)", "b => b.length")
    check("source list rendered", n_sources > 0, f"{n_sources} sources")

    # Model output must never become markup.
    injected = page.eval_on_selector_all("#ask-thread script", "s => s.length")
    check("no script injected from model output", injected == 0)

    # -- clicking a citation opens the panel and renders the PDF page --------
    if n_chips:
        page.click("#ask-thread .cite >> nth=0")
        check("source panel opens", page.is_visible("#src-panel"))
        page.wait_for_selector("#src-img:not(.hidden), #src-text:not(.hidden)",
                               timeout=60_000)
        rendered = page.eval_on_selector(
            "#src-img", "i => !i.classList.contains('hidden') && i.naturalWidth > 0")
        check("citation renders the source page", bool(rendered))
        check("clicked chip is highlighted",
              page.eval_on_selector_all("#ask-thread .cite.on", "c => c.length") == 1)
        check("panel names the source", len(page.inner_text("#src-title")) > 0,
              page.inner_text("#src-title")[:40])
        page.click("#src-close")
        check("panel closes", not page.is_visible("#src-panel"))

    # -- the composer is disabled until something is uploaded ----------------
    page.click('.tab-btn[data-tab="scratch"]')
    check("scratch composer disabled before upload",
          page.get_attribute("#scratch-input", "disabled") is not None)

    # -- clearing a thread empties it ---------------------------------------
    page.click('.tab-btn[data-tab="ask"]')
    page.click("#ask-clear")
    check("clear empties the thread",
          page.eval_on_selector("#ask-thread", "t => t.children.length") == 0)

    # -- the page never logged an error -------------------------------------
    check("no console errors", not ERRORS, "; ".join(ERRORS[:2]))


ERRORS: list[str] = []


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("playwright not installed - skipping UI tests")
        return 0

    with Server() as server:
        with sync_playwright() as p:
            try:
                browser = p.chromium.launch(headless=not HEADED)
            except Exception as exc:
                print(f"no browser available, skipping UI tests: "
                      f"{str(exc).splitlines()[0][:80]}")
                return 0
            page = browser.new_page(viewport={"width": 1400, "height": 900})
            page.on("console", lambda m: ERRORS.append(m.text)
                    if m.type == "error" else None)
            page.on("pageerror", lambda e: ERRORS.append(str(e)))
            try:
                run(page, server.url)
            except Exception as exc:
                # A failed check often makes the next step impossible - with no
                # tab active there is nothing to type into - and an exception
                # here would otherwise discard the checks that did run.
                check("run completed", False, f"{type(exc).__name__}: "
                                              f"{str(exc).splitlines()[0][:90]}")
            finally:
                browser.close()

    failed = sum(1 for _, s in CHECKS if s == "FAIL")
    print(f"\n{len(CHECKS) - failed}/{len(CHECKS)} UI check(s) passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
