"""
Give a chunk back the context its page had.

A chunk is embedded as a bare passage, but it was written inside a paper, under
a heading, on a subject the sentence itself never restates. "The best results
obtained were a combination of batch size 8 and learning rate of 0.001" does
not say which model, which paper, or that it is a result - all of which the
reader of the original page could see at a glance.

The median chunk in this corpus is 342 characters. At that length the missing
context is most of the meaning, and two chunks from different papers reporting
different accuracies embed almost identically.

So the vector is computed from a prefixed string while the stored text stays
exactly as it was. Retrieval matches on context plus passage; citations, the
source panel and the answer all still show the passage alone. Nothing the user
sees changes.

The prefix is built from fields already on the chunk rather than generated by a
model. An LLM-written one sentence per chunk is the stronger version of this
idea and is worth measuring later, but it costs one call per chunk - about four
thousand for this library - where this costs nothing and can be backfilled in
seconds.
"""

from __future__ import annotations

import re

_MAX_TITLE = 140
_MAX_SECTION = 80


def _tidy(text: str | None, limit: int) -> str:
    t = re.sub(r"\s+", " ", (text or "")).strip(" .,;:-–—")
    return t[:limit].strip()


def context_prefix(
    title: str | None,
    section_name: str | None = None,
    subsection_name: str | None = None,
) -> str:
    """
    A one-line header for a chunk: what paper, what section.

    Empty when there is nothing useful to say, so a chunk with no known title
    and no heading is embedded exactly as before rather than being given a
    misleading preamble.
    """
    parts = [p for p in (
        _tidy(title, _MAX_TITLE),
        _tidy(section_name, _MAX_SECTION),
        _tidy(subsection_name, _MAX_SECTION),
    ) if p]
    if not parts:
        return ""
    # De-duplicate: a subsection is often a repeat of its parent heading, and
    # repeating it twice only skews the vector.
    seen: list[str] = []
    for p in parts:
        if p.lower() not in {s.lower() for s in seen}:
            seen.append(p)
    return " | ".join(seen)


def embedding_text(
    text: str,
    title: str | None,
    section_name: str | None = None,
    subsection_name: str | None = None,
) -> str:
    """What to embed for a chunk. The stored text is never changed."""
    prefix = context_prefix(title, section_name, subsection_name)
    return f"{prefix}\n\n{text}" if prefix else text
